### ISSUE TITLE
Look into speed control for shooter wheels (With PID)

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/PlyBot2017#10]
Put the robot on it's side for testing.

**Comment by ammenzl7** [comment]
Use CAN IDs 5 and 6.

**Comment by ammenzl7** [comment]
- [x] Find Max Speed of the motors (Put the robot on blocks, floor it).

**Comment by ammenzl7** [comment]
Need to tune the PID values (Specifically the I value).

**Comment by ammenzl7** [comment]
PID has been tuned, the values are:

P: 0.3
I: 0.001
D: 0.0
F: 0.12

**Comment by abcurrie** [comment]
Thinking about these values they seem about right.  Remember I said the FF gain was to ratio the output to the setpoint to get you mostly there.   If you remember the max speed setpoint was about 8000 units, (whatever they are).  The output is at 100% or 1024 units to do this.  Therefore the ratio of output units to setpoint units is 10024/80000 or about the 0.12 that we ended up with.  The P gain therefore only has to take up a little slack and can be tuned fairly aggressively.  Pretty cool huh!?

 

Sandy Currie
