### ISSUE TITLE
Look into motion recording

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/PlyBot2017#13]

**Comment by Shalmezad** [comment]
I have some pre-emptive work started in the motion_recording branch. Would like to test this on PlyBot later today.
Please do not deploy or merge that branch (yet).

**Comment by mike-r** [comment]
OK. 

When are you coming in?

Mike

**Comment by Shalmezad** [comment]
Should be in around 5. 
Be sure to let the students know that if they run into trouble, they should describe what problems they're having in the issue and add the "help wanted" label (right hand side). It'll help make problems a lot quicker to find.

**Comment by mike-r** [comment]
Great. 

See you then
Mike
