### ISSUE TITLE
Make sure everyone is using the latest FRC update

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/PlyBot2017#15]
Latest version is 2017.2.1

- [x] Andrew M.
- [x] Jessica K.
- [x] Shiva S.
- [x] Derek Y.
- [x] Cody K.
- [x] David W.
- [ ] Jon G.
- [x] Kaedon C.
- [ ] Richard W.
- [x] Colin W.
- [x] Mr. Currie
- [x] Mr. Wardin
- [x] Mr. Rehberg
- [ ] Mr. Woods
- [x] Programmer 1
- [x] Programmer 3

**Comment by ammenzl7** [comment]
Once you are updated, confirm with Andrew.

**Comment by wittcd** [comment]
i am confirming

**Comment by ghost** [comment]
Please do not check yourself off before checking.
