### ISSUE TITLE
Improve delinearization to account for deadband

### ISSUE THREAD

**Issue by ammenzl7** [The-Charge/PlyBot2017#16]

**Comment by wittcd** [comment]
Will do several stages
1) 1:1 Linear, but shifted to account for deadband
2) Linear, but slope edited to account for deadband

**Comment by wittcd** [comment]
I need to know exactly what each of these commands does:

deadbandCheck();

delinearize();

**Comment by wittcd** [comment]
stage 1 done,
stage 2 ready for testing

**Comment by wittcd** [comment]
Finished
