### ISSUE TITLE
Investigate MotionMagic

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2017#20]
There is a new mode to the TalonSRX called MotionMagic that can simplify profile control.
Program this for testing and determine future path.

**Comment by JessicaKline** [comment]
Talon generated motion profile 
specify cruising velocity, acceleration and PIDF
Follows trapezoidal profile

https://www.chiefdelphi.com/media/papers/download/4772 
        End of this paper best explanation I found

**Comment by abcurrie** [comment]
HI Sandy,



There's a new manual version going out soon, but I can give you the basic information in the meantime.




Motion Magic is a new control mode for Talon SRX that provides the benefits of Motion Profiling without needing to generate the profile data.  You use the MotionMagic control paramter when setting the Talon Control Mode.




The first step for Motion Magic is setting up your position PIDF values as normal (see the Soft. Ref. Manual).  You then use two additional calls (setMotionMagicAcceleration(double) and setMotionMagicCruiseVelocity(double)) to set the desired acceleration and cruise velocity parameters.




Once this has been done, you can use set() calls as normal to set the position that Talon will move to, and the motion will follow a trapezoidal motion profile (as described in the motion profiling documentation).




That's it!  It gives you flexibility to have all movements follow a trapezoidal motion profile without actually generating the profile points.




Let me know if you have any additional questions.




Regards,




Jacob Caporuscio

Software/Hardware Engineer

CTR Electronics

**Comment by JessicaKline** [comment]
Need to Know: RPM's of what?

**Comment by JessicaKline** [comment]
new manual out->http://www.ctr-electronics.com/downloads/pdf/Talon%20SRX%20Software%20Reference%20Manual.pdf 
pg 68

**Comment by ammenzl7** [comment]
Motion Magic works, PID has been tuned, need to change it to make the command run correctly without running it twice. Also need to replace DriveXFeet with Motion Magic.

**Comment by JessicaKline** [comment]
Operates on one click now. replace DriveXFeet still needed.
