### ISSUE TITLE
Test out new talon feature to limit current

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2017#21]
There is a new feature on the can talon to set a max current limit.  
This may be helpful to prevent burning out motors and conserving power

**Comment by ghost** [comment]
I was unable to find any methods related to this.

**Comment by abcurrie** [comment]
Where did you look?

 

What about these calls:

 

SetCurrentLimEnable(long, boolean) - Static method in class com.ctre.CanTalonJNI

 

setCurrentLimit(int) - Method in class com.ctre.CANTalon

 

 

Sandy Currie

**Comment by ghost** [comment]
I have set the current limit on all four motors to 4 amps. This needs to be tuned.

**Comment by ghost** [comment]
To do:
-adjust default value.
-add read and write to the smart dashboard. 
-add commands to turn it on and off.
