### ISSUE TITLE
Install can light libraries for everyone

### ISSUE THREAD

**Issue by abcurrie** [The-Charge/PlyBot2017#31]
- [x] Andrew M.
- [x] Jessica K.
- [x] Shiva S.
- [x] Derek Y.
- [x] Cody K.
- [x] David W.
- [ ] Jon G.
- [x] Kaedon C.
- [ ] Richard W.
- [ ] Colin W.
- [ ] Mr. Currie
- [ ] Mr. Wardin
- [ ] Mr. Rehberg
- [ ] Mr. Woods
- [ ] Programmer 1
- [ ] Programmer 3

**Comment by abcurrie** [comment]
http://www.mindsensors.com/content/88-cheat-sheet-for-canlight-led-strip-controller-kit-for-frc-robots

**Comment by abcurrie** [comment]
Installation of this library:
Locate 'wpilib' folder on your computer (this is generally here: C:/Users/username/wpilib)
('username' is folder for the user that is logged in.)
Open folder 'wpilib/user',
Unzip the downloaded zip file,
This zip has 'user' folder, copy contents of 'user' folder to your wpilib/user folder. 
(if there is a conflict with existing files, replace them with newly downloaded files).

**Comment by Menzla** [comment]
- [ ] Andrew M.
- [ ] Jessica K.
- [ ] Shiva S.
- [ ] Derek Y.
- [ ] Cody K.
- [ ] David W.
- [ ] Jon G.
- [ ] Kaedon C.
- [ ] Richard W.
- [ ] Colin W.
- [ ] Mr. Currie
- [ ] Mr. Wardin
- [ ] Mr. Rehberg
- [ ] Mr. Woods
- [ ] Programmer 1
- [ ] Programmer 3
